-- MySQL Script generated by MySQL Workbench
-- Tue Jan 10 20:17:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Explore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Explore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Explore` DEFAULT CHARACTER SET utf8 ;
USE `Explore` ;

-- -----------------------------------------------------
-- Table `Explore`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Explore`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(36) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `activationLink` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Explore`.`userRefreshToken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Explore`.`userRefreshToken` (
  `us_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RefreshToken` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`us_id`),
  CONSTRAINT `id`
    FOREIGN KEY (`us_id`)
    REFERENCES `Explore`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
