-- MySQL Script generated by MySQL Workbench
-- Thu Jan 12 08:38:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Explore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Explore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Explore` DEFAULT CHARACTER SET utf8 ;
USE `Explore` ;

-- -----------------------------------------------------
-- Table `Explore`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Explore`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(36) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `activationLink` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickName_UNIQUE` (`nickName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Explore`.`user_refresh_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Explore`.`user_refresh_token` (
  `us_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RefreshToken` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`us_id`),
  UNIQUE INDEX `us_id_UNIQUE` (`us_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`us_id`)
    REFERENCES `Explore`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Explore`.`dialogues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Explore`.`dialogues` (
  `id_d` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id1` INT UNSIGNED NOT NULL,
  `user_id2` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id_d`),
  INDEX `id_idx` (`user_id1` ASC, `user_id2` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`user_id1` , `user_id2`)
    REFERENCES `Explore`.`users` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Explore`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Explore`.`messages` (
  `id_m` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_id` INT UNSIGNED NOT NULL,
  `target_id` INT UNSIGNED NOT NULL,
  `text` TINYTEXT NULL DEFAULT NULL,
  `created_ad` DATETIME NOT NULL,
  PRIMARY KEY (`id_m`),
  INDEX `id_idx` (`target_id` ASC, `source_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`target_id` , `source_id`)
    REFERENCES `Explore`.`users` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
